export { default as Home } from '@/pages/Home'
export { default as Players } from '@/pages/Players'
export { default as PlayerDetail } from '@/pages/PlayerDetail'
export { default as Profile } from '@/pages/Profile'
export { default as Talk } from '@/pages/Talk'
export { default as Bookmark } from '@/pages/Bookmark'
export { default as NotFound } from '@/pages/NotFound'
